In [1]:
from numpy import array
import numpy as np

## 1. Matrix Multiplication: Element-wise

In [2]:
A = array([
 [1, 2, 3],
 [4, 5, 6]
])
print("A's shape: {}".format(A.shape,))
print(A)

A's shape: (2, 3)
[[1 2 3]
 [4 5 6]]


In [3]:
B =  array([
 [2, 4, 6],
 [8, 10, 12]
])
print("B's shape: {}".format(B.shape,))
print(B)

B's shape: (2, 3)
[[ 2  4  6]
 [ 8 10 12]]


In [4]:
C = A * B
print("C's shape: {}".format(C.shape,))
print(C)

C's shape: (2, 3)
[[ 2  8 18]
 [32 50 72]]


## 2. Matrix-Vector Multiplication: Broadcasting

In [5]:
A = array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])
print("A's shape: {}".format(A.shape,))
print(A)

A's shape: (3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [6]:
B = array([2, 3])
print("B's shape: {}".format(B.shape,))
print(B)

B's shape: (2,)
[2 3]


In [7]:
C = A + B
print("C's shape: {}".format(C.shape,))
print(C)

C's shape: (3, 2)
[[3 5]
 [5 7]
 [7 9]]


## 3. Dot Product

In [8]:
A = array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])
print("A's shape: {}\n".format(A.shape,))
print(A)


A's shape: (3, 2)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
B = array([
    [1, 2], 
    [3, 4]
])
print("B's shape: {}\n".format(B.shape,))
print(B)

B's shape: (2, 2)

[[1 2]
 [3 4]]


In [10]:
C = A.dot(B)
print("C's shape: {}\n".format(C.shape,))
print(C)

C's shape: (3, 2)

[[ 7 10]
 [15 22]
 [23 34]]


## 4. Python Loops vs. Numpy Matrix Operations

In [11]:
from numpy import random
import timeit

X = random.randint(10, size=(10, 10))
Y = random.randint(10, size=(10, 10))

print("Matrix X:\n {}".format(X))
print("Matrix Y:\n {}".format(Y))

Matrix X:
 [[1 6 0 1 5 8 7 9 8 8]
 [6 8 5 1 7 8 6 0 1 0]
 [2 5 7 7 7 7 5 7 5 7]
 [7 1 3 3 9 4 2 2 3 8]
 [7 1 6 9 8 9 8 5 4 8]
 [7 7 9 7 3 1 4 2 2 0]
 [3 0 2 5 7 8 4 1 2 1]
 [5 6 4 8 5 7 3 9 2 0]
 [7 9 7 3 4 3 1 9 9 3]
 [8 3 6 5 3 4 2 4 9 4]]
Matrix Y:
 [[7 1 6 2 0 9 6 6 0 2]
 [3 4 6 3 2 9 7 3 5 0]
 [5 6 1 3 2 2 9 7 7 0]
 [0 2 6 9 6 3 7 9 4 9]
 [9 9 2 7 5 6 1 7 7 1]
 [1 9 9 4 9 6 0 1 2 4]
 [1 6 5 7 7 8 2 0 0 5]
 [9 4 4 2 8 4 2 0 3 8]
 [1 6 9 9 5 5 4 0 5 0]
 [2 3 9 6 2 7 3 1 7 0]]


In [12]:
def add_python(X, Y):
    return [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]

def add_numpy(X, Y):
    return np.add(X, Y)

In [ ]:
timeit.timeit('add_numpy(X, Y)', globals=globals())

0.6987719569879118

In [ ]:
timeit.timeit('add_python(X, Y)', globals=globals())

## 5. Normalization

In [ ]:
from numpy import array
import numpy as np

a = array([0.1, 5, 12, 100])
print("Mean: {}".format(a.mean(axis=0)))
a -= a.mean(axis=0)
print("After deduct mean: {}".format(a))


In [ ]:
print("Standard Deviation: {}".format(a.std(axis=0)))
a /= a.std(axis=0)
print("After normalization: {}".format(a))

In [ ]:
print("Standard Deviation of the normalized array: {}".format(a.std(axis=0)))

## 6. Chain Rules

In [ ]:
# sympy does symbolic differentiation
import sympy as sp
from sympy import *

x = sp.symbols('x')
y = sp.symbols('y')

f = 2*x
g = pow(f, 2)# g = f(x)**2

# Calculate the derivative to x
g_x_d = g.diff()

g_x_d

## 7. Gradient for a two variables function

In [ ]:
m=sp.Matrix([[x],[y]])
f = x**2-x*y

f_x_y_d = [sp.diff(f, i) for i in m]
f_x_y_d

## 8. Softmax Function

In [ ]:
def softmax(y):
    """Compute softmax values for each sets of scores in y."""
    return np.exp(y) / np.sum(np.exp(y), axis=0)

In [ ]:
# Let's say we want to classify: dog, pig, chickren, duck
scores = [11,12,13,14]
print(softmax(scores))

## 9. Activation Functions

### 1. Sigmod 

In [ ]:
#sigmoid activation function
def sigmoid(x, derivative=False):
    if(derivative==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

![Sigmoid](images/sigmoid.gif)

In [ ]:
sigmoid(1)